// Sentiment indicator definitions — metadata for all 13 sentiment indicators

import type { SentimentIndicatorDef } from '../types/sentiment.types';

export const SENTIMENT_INDICATOR_DEFS: SentimentIndicatorDef[] = [
  {
    code: 'SENT_NEWS',
    name: 'News Sentiment',
    category: 'sentiment',
    subcategory: 'news',
    params: [
      { name: 'lookback_hours', default: 24, min: 1, max: 168, description: 'Hours of news to consider' },
      { name: 'source_weight', default: 1, min: 0, max: 2, description: 'Premium source weight multiplier' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1h', '4h', '1d', '1w'],
    description: 'Entity-level sentiment score derived from news articles. 50 = neutral, >70 = bullish, <30 = bearish.',
  },
  {
    code: 'SENT_NEWS_MOM',
    name: 'News Sentiment Momentum',
    category: 'sentiment',
    subcategory: 'news',
    params: [
      { name: 'period', default: 24, min: 1, max: 168, description: 'Lookback period in hours' },
    ],
    outputRange: { min: -100, max: 100 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Rate of change in news sentiment. Positive = improving, negative = deteriorating.',
  },
  {
    code: 'SENT_SOCIAL',
    name: 'Social Sentiment',
    category: 'sentiment',
    subcategory: 'social',
    params: [
      { name: 'lookback_hours', default: 24, min: 1, max: 168, description: 'Hours of social data to consider' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Weighted average sentiment across social platforms (Twitter, Reddit, StockTwits). 50 = neutral.',
  },
  {
    code: 'SOCIAL_VOL',
    name: 'Social Volume',
    category: 'sentiment',
    subcategory: 'social',
    params: [
      { name: 'baseline_days', default: 7, min: 1, max: 30, description: 'Baseline period for average calculation' },
    ],
    outputRange: { min: 0, max: 999 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Relative social mention volume vs baseline average. 1.0 = normal, 3.0 = 3x normal.',
  },
  {
    code: 'SOCIAL_MOM',
    name: 'Social Momentum',
    category: 'sentiment',
    subcategory: 'social',
    params: [
      { name: 'period', default: 24, min: 1, max: 168, description: 'Lookback period in hours' },
    ],
    outputRange: { min: -100, max: 100 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Rate of change in social sentiment. Positive = improving, negative = deteriorating.',
  },
  {
    code: 'INST_FLOW',
    name: 'Institutional Flow',
    category: 'sentiment',
    subcategory: 'institutional',
    params: [
      { name: 'insider_weight', default: 30, min: 0, max: 100, description: 'Insider signal weight (%)' },
      { name: 'options_weight', default: 30, min: 0, max: 100, description: 'Options flow weight (%)' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1d', '1w', '1M'],
    description: 'Composite institutional flow: 13F filings + insider transactions + options flow + dark pool.',
  },
  {
    code: 'INSIDER',
    name: 'Insider Activity',
    category: 'sentiment',
    subcategory: 'institutional',
    params: [
      { name: 'lookback_days', default: 30, min: 7, max: 90, description: 'Days of insider activity to consider' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1d', '1w', '1M'],
    description: 'Insider buy/sell signal. >70 = cluster buying, <30 = cluster selling, 50 = neutral.',
  },
  {
    code: 'OPTIONS_FLOW',
    name: 'Options Flow',
    category: 'sentiment',
    subcategory: 'institutional',
    params: [
      { name: 'min_premium', default: 100000, min: 10000, max: 10000000, description: 'Minimum premium to include ($)' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Net bullish/bearish options activity score. >70 = bullish sweeps dominant, <30 = bearish.',
  },
  {
    code: 'PCR',
    name: 'Put/Call Ratio',
    category: 'sentiment',
    subcategory: 'institutional',
    params: [
      { name: 'lookback_days', default: 1, min: 1, max: 30, description: 'Lookback period' },
    ],
    outputRange: { min: 0, max: 999 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Put volume / call volume. Lower = more bullish. Typical range 0.5–1.5.',
  },
  {
    code: 'IV_RANK',
    name: 'Implied Vol Rank',
    category: 'sentiment',
    subcategory: 'earnings',
    params: [],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1d'],
    description: 'Current implied volatility percentile vs 52-week range. >80 = IV elevated.',
  },
  {
    code: 'EARN_SENT',
    name: 'Earnings Sentiment',
    category: 'sentiment',
    subcategory: 'earnings',
    params: [],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1d'],
    description: 'Pre-earnings composite: revision momentum + whisper gap + pre-earnings sentiment.',
  },
  {
    code: 'EVENT_CAT',
    name: 'Event Catalyst',
    category: 'sentiment',
    subcategory: 'event',
    params: [
      { name: 'days_ahead', default: 10, min: 1, max: 30, description: 'Days ahead to look for catalysts' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1d'],
    description: 'Proximity and expected impact of upcoming catalysts. Higher = more catalyst activity ahead.',
  },
  {
    code: 'SENT_COMPOSITE',
    name: 'Composite Sentiment',
    category: 'sentiment',
    subcategory: 'composite',
    params: [
      { name: 'news_weight', default: 25, min: 0, max: 100, description: 'News weight (%)' },
      { name: 'social_weight', default: 15, min: 0, max: 100, description: 'Social weight (%)' },
      { name: 'inst_weight', default: 20, min: 0, max: 100, description: 'Institutional weight (%)' },
    ],
    outputRange: { min: 0, max: 100 },
    availableTimeframes: ['1h', '4h', '1d'],
    description: 'Weighted blend of all sentiment indicators. 50 = neutral, >70 = bullish, <30 = bearish.',
  },
];
